### ISSUE TITLE
(Global view) posts that are deleted stay in the stream.

### ISSUE THREAD

**Issue by keichan34** [matigo/nice_social#182] opened 2015-09-06 14:01 UTC
They stay in the stream until the next reload of the page, with a relative post time of "NaN years ago".

**Comment by matigo** [comment] 2015-09-06 14:02
That problem is back? Grr ...

**Comment by matigo** [comment] 2015-09-08 07:23
Ah, this is a duplicate of #121. Still "grr", but will attack issue over there.

**Closed by matigo** 2015-09-08 07:23 UTC
Labels: bug
